(ns ansatz.bundled-store-roots-test
  "The bundled Init store is the transitive dependency closure of an explicit root manifest
   (scripts/init-store-roots.txt), regenerated by scripts/regen-bundled-store.sh. This test
   is the guard rail on that arrangement: every root must actually resolve in the loaded
   store.

   It exists because the store previously drifted silently. The shipped store was a raw
   `head -n 200000` prefix of a full `lean4export Init` dump with no script and no root
   list, and the cut excluded ~20 constants the omega tactic references — including all of
   `Lean.Omega.bmod_*`. Nothing failed: `ansatz.attrs`/`ansatz.matchers` skip names absent
   from the env, and omega's `add-div-bounds` swallows lookup failures in a bare
   `catch Exception`, so the gap only ever showed up as tactics quietly declining to fire.
   A missing constant now fails a test instead."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [ansatz.core :as a]))

(def ^:private manifest-path "scripts/init-store-roots.txt")

(defn- roots []
  (let [f (io/file manifest-path)]
    (when (.exists f)
      (->> (str/split-lines (slurp f))
           (map str/trim)
           (remove #(or (str/blank? %) (str/starts-with? % "#")))))))

(deftest every-root-in-the-manifest-resolves
  (binding [a/*verbose* false]
    (a/load-init!)
    (let [rs (roots)]
      (is (some? rs)
          (str manifest-path " not found — run the test suite from the project root"))
      (when rs
        (testing "the manifest is non-trivial"
          (is (< 2000 (count rs))))
        (testing "every root resolves in the bundled store"
          (let [missing (remove a/has-constant? rs)]
            (is (empty? missing)
                (str (count missing) " root(s) absent from the bundled store — the store and "
                     manifest-path " have drifted; re-run scripts/regen-bundled-store.sh. "
                     "First few: " (pr-str (take 10 missing))))))))))

(def ^:private omega-constants
  "Constants the omega tactic's proof builder needs in order to certify division/modulo
   bounds and bmod (hard-equality) elimination. Each of these was absent from the previous
   bundled store."
  ["Decidable.not_iff"
   "Decidable.not_or_of_imp"
   "Int.emod_eq_zero_of_dvd"
   "Int.emod_pos_of_not_dvd"
   "Int.lt_mul_ediv_self_add"
   "Int.lt_or_gt_of_ne"
   "Int.mul_ediv_self_le"
   "Lean.Omega.bmod_sat"
   "Lean.Omega.bmod_coeffs"
   "Lean.Omega.bmod_div_term"
   "Lean.Omega.IntList.bmod"
   "Nat.div_mul_cancel"
   "Nat.emod_pos_of_not_dvd"
   "Nat.mod_eq_zero_of_dvd"
   "Nat.mul_two"])

(def ^:private core-spellings
  "omega_proof.clj also references five names that do not exist in Lean core's `Init` under
   those spellings — they are Mathlib spellings or typos (`not_and_or`, `not_imp`,
   `iff_iff_and_or_not_and_not`, `Int.ofNat.eq_def`, `Lean.Omega.Coeffs.bmod_coeffs`). The
   store ships the correct core constants, so fixing those references is a pure rename."
  ["Decidable.not_and_iff_not_or_not"
   "Classical.not_and_iff_not_or_not"
   "Classical.not_imp"
   "Decidable.not_imp_iff_and_not"
   "Decidable.iff_iff_and_or_not_and_not"
   "Int.ofNat_eq_natCast"
   "Lean.Omega.Coeffs.bmod"
   "Lean.Omega.Coeffs.bmod_length"])

(deftest omega-constants-resolve
  (binding [a/*verbose* false]
    (a/load-init!)
    (testing "omega's div/mod and bmod constants are in the bundled store"
      (doseq [n omega-constants]
        (is (a/has-constant? n) (str n " missing from the bundled Init store"))))
    (testing "correct core spellings for omega_proof.clj's misspelled references"
      (doseq [n core-spellings]
        (is (a/has-constant? n) (str n " missing from the bundled Init store"))))))
