(ns ansatz.kernel-soundness-test
  "Audit of the Java kernel against the Lean 4 kernel soundness fixes that landed upstream
   between March and August 2026 (issue #77). One section per upstream PR. Every section pins
   the invariant the PR establishes; where our kernel is still exposed the test is `^:wip`
   (the suite excludes `:wip`), encodes the concrete unsound input, and names the PR — so the
   exposure is tracked by a test that turns green when the kernel is fixed.

   All fixtures are built through the kernel's own admission paths (`check-constant`,
   `check-inductive-bundle`) over the bundled Init tier; nothing here needs Mathlib.

   Shared gadget (used by #14806 and #14807): definitional equality in the kernel is a sound
   but INCOMPLETE semi-decision procedure and therefore NOT transitive. Proof irrelevance makes
   `ksF ax ≡ ksF (KsAc.intro 0 axAll)` (both arguments are proofs of `KsAc 0`); iota makes
   `ksF (KsAc.intro 0 axAll) ≡ 7`; but `ksF ax` is stuck on the axiom, so `ksF ax ≢ 7`. With
   `ksA := ksF ax` and `ksB := ksF (KsAc.intro 0 axAll)`: ksA ≡ ksB, ksB ≡ 7, ksA ≢ 7. This is
   the same shape upstream's `kernel_is_def_eq_equiv_manager_*.lean` tests use (there with
   `Acc.rec` and an opaque accessibility proof)."
  (:require [clojure.test :refer [deftest testing is]]
            [ansatz.test-env :as te]
            [ansatz.kernel.env :as env]
            [ansatz.kernel.expr :as e]
            [ansatz.kernel.level :as lvl]
            [ansatz.kernel.name :as name]
            [ansatz.export.parser :as parser]
            [ansatz.export.replay :as replay])
  (:import [ansatz.kernel TypeChecker Reducer Env Expr Level ConstantInfo ConstantInfo$RecursorRule
            InductiveBundle Name]
           [java.math BigInteger]))

;; ============================================================
;; Helpers
;; ============================================================

(def ^:private fuel 5000000)

(defn- n [s] (name/from-string s))
(defn- c
  ([s] (e/const' (n s) []))
  ([s lvls] (e/const' (n s) lvls)))
(def ^:private l0 lvl/zero)
(def ^:private l1 (lvl/succ lvl/zero))
(def ^:private l2 (lvl/succ l1))
(def ^:private prop (e/sort' l0))
(def ^:private type0 (e/sort' l1))
(defn- pi [nm dom body] (e/forall' nm dom body :default))
(defn- lam [nm dom body] (e/lam nm dom body :default))
(defn- lit [k] (e/lit-nat k))
(defn- bv [i] (e/bvar i))

(def ^:private E (delay @te/bundled-init-env))

(defn- admit
  "check-constant; returns the new env."
  [env ci]
  (env/check-constant env ci fuel))

(defn- rejection
  "The kernel's error message if `ci` is rejected, nil if it is admitted."
  [env ci]
  (try (env/check-constant env ci fuel) nil
       (catch Throwable ex (or (.getMessage ex) (str ex)))))

(defn- bundle-rejection
  [env bundle]
  (try (env/check-inductive-bundle env bundle fuel) nil
       (catch Throwable ex (or (.getMessage ex) (str ex)))))

(defn- fresh-tc
  (^TypeChecker [env] (doto (TypeChecker. env) (.setFuel fuel)))
  (^TypeChecker [env lps]
   ;; safety byte 0 = safe (TypeChecker.DEFN_SAFE is package-private)
   (doto (TypeChecker. env (byte 0) (into-array Object lps)) (.setFuel fuel))))

(defn- whnf [env ex] (.whnf (Reducer. env) ex))

(defn- tc-whnf
  "TypeChecker.whnfExpr (package-private): whnf in the checker's own local context."
  [^TypeChecker tc ex]
  (let [m (doto (.getDeclaredMethod TypeChecker "whnfExpr" (into-array Class [Expr]))
            (.setAccessible true))]
    (.invoke m tc (object-array [ex]))))

(defn- declare-inductive
  "Admit a (non-nested) inductive block through the kernel. A bundle without recursors gets
   none generated by `checkInductiveBundle` (it only VALIDATES imported recursors against the
   generator), so generate them first with the kernel's own generator — the path nested
   inductives take (InductiveChecker.generateAndCheckRecursors) — then admit the full bundle,
   which re-validates the generated recursors exactly as it would imported ones."
  [env lps nparams inds ctors]
  (let [bundle0 (env/mk-inductive-bundle lps nparams false inds ctors [])
        klass (Class/forName "ansatz.kernel.InductiveChecker")
        ctor (doto (.getDeclaredConstructor klass (into-array Class [Env InductiveBundle Long/TYPE]))
               (.setAccessible true))
        ic (.newInstance ctor (object-array [env bundle0 (long fuel)]))
        m (doto (.getDeclaredMethod klass "generateAndCheckRecursors" (into-array Class []))
            (.setAccessible true))
        recs (vec (.invoke m ic (object-array [])))]
    (env/check-inductive-bundle env (env/mk-inductive-bundle lps nparams false inds ctors recs) fuel)))

(defn- level-args
  "Universe arguments for constant `s` in the order of its declared level params, from a
   name→Level map (so tests do not hard-code Lean's level-parameter ordering)."
  [env s m]
  (mapv (fn [p] (get m (str p))) (.levelParams ^ConstantInfo (env/lookup env (n s)))))

;; ============================================================
;; Shared fixture: the non-transitive defeq gadget (KsAc / ksF / ksA / ksB)
;; ============================================================

(def ^:private Nat (delay (c "Nat")))
(def ^:private Bool (delay (c "Bool")))

(defn- ksac-ctor-type []
  ;; KsAc.intro : (n : Nat) → (h : (m : Nat) → KsAc m) → KsAc n
  (pi "n" @Nat
      (pi "h" (pi "m" @Nat (e/app (c "KsAc") (bv 0)))
          (e/app (c "KsAc") (bv 1)))))

(defn- with-gadget
  "Env extended with KsAc (an inductive predicate with large elimination, like Acc), the
   axioms, and the definitions ksF / ksA / ksB / ksG."
  [env]
  (let [KsAc (n "KsAc") intro (n "KsAc.intro")
        env (declare-inductive
             env [] 0
             [(env/mk-induct KsAc [] (pi "n" @Nat prop)
                             :num-params 0 :num-indices 1 :all [KsAc] :ctors [intro] :rec? true)]
             [(env/mk-ctor intro [] (ksac-ctor-type) KsAc 0 0 2)])
        ksac0 (e/app (c "KsAc") (lit 0))
        env (admit env (env/mk-axiom (n "ksAx") [] ksac0))
        env (admit env (env/mk-axiom (n "ksAxAll") [] (pi "m" @Nat (e/app (c "KsAc") (bv 0)))))
        env (admit env (env/mk-axiom (n "ksG") [] (e/arrow @Nat @Nat)))
        ;; ksF (h : KsAc 0) : Nat := KsAc.rec.{1} (fun n _ => Nat) (fun n h ih => 7) 0 h
        motive (lam "n" @Nat (lam "t" (e/app (c "KsAc") (bv 0)) @Nat))
        minor (lam "n" @Nat
                   (lam "h" (pi "m" @Nat (e/app (c "KsAc") (bv 0)))
                        (lam "ih" (pi "m" @Nat @Nat) (lit 7))))
        ksF-body (lam "h" ksac0 (e/app* (c "KsAc.rec" [l1]) motive minor (lit 0) (bv 0)))
        env (admit env (env/mk-def (n "ksF") [] (e/arrow ksac0 @Nat) ksF-body :hints {:regular 1}))
        env (admit env (env/mk-def (n "ksA") [] @Nat (e/app (c "ksF") (c "ksAx")) :hints {:regular 2}))
        env (admit env (env/mk-def (n "ksB") [] @Nat
                                   (e/app (c "ksF") (e/app* (c "KsAc.intro") (lit 0) (c "ksAxAll")))
                                   :hints {:regular 2}))]
    env))

(def ^:private gadget-env (delay (with-gadget @E)))

(deftest gadget-is-non-transitive
  (testing "the fixture behaves as designed: ksA ≡ ksB, ksB ≡ 7, but ksA ≢ 7 (each on a FRESH checker)"
    (let [env @gadget-env]
      (is (.isDefEq (fresh-tc env) (c "ksA") (c "ksB")) "proof irrelevance under the same-definition argument shortcut")
      (is (.isDefEq (fresh-tc env) (c "ksB") (lit 7)) "iota on the constructor argument")
      (is (not (.isDefEq (fresh-tc env) (c "ksA") (lit 7))) "stuck on the axiom — not defeq")
      (is (not (.isDefEq (fresh-tc env)
                         (e/app (lam "x" @Nat (e/app (c "ksG") (bv 0))) (c "ksA"))
                         (e/app (c "ksG") (lit 7))))
          "congruence over ksA vs 7 is false on a fresh checker"))))

;; ============================================================
;; #14806 — is_def_eq caching must be order-independent
;; ============================================================
;;
;; Upstream: the union-find `equiv_manager` recorded successful is_def_eq pairs and returned
;; true for any two members of the same class — i.e. it took the TRANSITIVE closure. Since
;; is_def_eq is not transitive, the answer to a query then depended on which pairs had been
;; asked before. #14806 deletes equiv_manager and replaces it with a plain pair-keyed success
;; cache (`m_success`, `succeeded_before`/`cache_success`), symmetric to `m_failure`.
;;
;; Ours: TypeChecker.isDefEq (TypeChecker.java:1068-1079) calls `eqvManager.addEquiv(t, s)`
;; on every success, and quickIsDefEq (:1129-1133) consults `eqvManager.isEquiv`, which
;; MERGES classes as it recurses (EquivManager.java:96-152, `if (result) merge(r1, r2)`).
;; That is the pre-#14806 design verbatim. The identity/structural failure caches
;; (:1812-1856) are pair-keyed and fine; the exposure is the positive cache.

(deftest ^:wip pr14806-defeq-cache-is-order-independent
  (testing "upstream leanprover/lean4#14806 — after ksA ≡ ksB and ksB ≡ 7 were recorded on ONE
   checker, `ksG ksA =?= ksG 7` must still be false (a fresh checker says false). The beta redex
   on the left forces the post-whnf_core quick check (use_hash=false), which walks the two
   applications structurally and finds ksA and 7 in the same union-find class."
    (let [env @gadget-env
          tc (fresh-tc env)
          t (e/app (lam "x" @Nat (e/app (c "ksG") (bv 0))) (c "ksA"))
          s (e/app (c "ksG") (lit 7))]
      (is (.isDefEq tc (c "ksA") (c "ksB")))
      (is (.isDefEq tc (c "ksB") (lit 7)))
      (is (not (.isDefEq tc t s))
          "EXPOSED: transitive closure through the equiv manager (fix: pair-keyed success cache)"))))

;; ============================================================
;; #14631 — projection defeq compares the structure name
;; ============================================================
;;
;; Upstream: is_def_eq_core's proj/proj case and equiv_manager compared only the field index
;; and the projected expression; #14631 adds `proj_sname(t) == proj_sname(s)`. Per lean4lean's
;; divergences.md the comparison is redundant ONLY because `infer_proj` already rejects
;; `.proj S i e` unless the type of `e` whnfs to an application of `S` itself
;; (type_checker.cpp:278-280, `if (I_name != proj_sname(e)) throw invalid_proj_exception`).
;;
;; Ours (before this audit): the PROJ case of inferTypeCore (TypeChecker.java:929-976) took the
;; inductive from the whnf'd type head and NEVER compared it against the projection's own
;; structure name `e.o0`; Step 5b of isDefEqCoreImpl (:1361) compares only `longVal`; EquivManager
;; PROJ (:129-132) explicitly ignores the name. FIXED here with Lean's one-line infer_proj check
;; (TypeChecker.java PROJ case: `if (!head.o0.equals(e.o0)) throw`). With that guard every
;; projection that reaches isDefEq / EquivManager has been through inference, so — exactly as
;; lean4lean argues — the name comparison in the defeq paths is redundant and left as is.

(defn- prod-pair []
  (e/app* (c "Prod.mk" [l0 l0]) @Nat @Nat (lit 1) (lit 2)))

(deftest pr14631-well-named-projection-is-accepted
  (let [env @E
        good (env/mk-def (n "ksGoodProj") [] @Nat (e/proj (n "Prod") 0 (prod-pair)))]
    (is (nil? (rejection env good)))
    (is (= (lit 1) (whnf env (e/proj (n "Prod") 0 (prod-pair)))))))

(deftest pr14631-projection-structure-name-must-match
  (testing "upstream leanprover/lean4#14631 (and infer_proj) — `(Prod.mk 1 2).proj Bool 0` names
   a structure that is not the type of the projected term and must be an invalid projection"
    (let [env @E
          bad (env/mk-def (n "ksBadProj") [] @Nat (e/proj (n "Bool") 0 (prod-pair)))]
      (is (re-find #"invalid projection" (str (rejection env bad)))
          "inferTypeCore PROJ must compare the projection's structure name with the type head"))))

;; ============================================================
;; #14807 — is_prop via ensure_sort, not whnf-then-syntactic-Sort
;; ============================================================
;;
;; Upstream: `is_prop(e)` was `whnf(infer_type(e)) == Prop`, so when the sort of a type is
;; STUCK (whnf does not reach a Sort) the answer was "not a proposition", and infer_proj then
;; allowed extracting a data field out of a proof. #14807 makes it `ensure_sort(infer_type(e))`,
;; which throws on a stuck sort. The upstream test builds an inductive `Owner (h : P) : gate h`
;; whose sort `gate h` K-reduces to `Prop` for the generic `h` but is stuck for a specific
;; witness `w : a = c` because `a ≢ c` directly (non-transitivity again).
;;
;; Ours: TypeChecker.isProp (TypeChecker.java:555-558) is
;;   `Expr t = whnf(inferTypeOnly(e)); return t.tag == SORT && level.tag == ZERO;`
;; — exactly the pre-fix shape: a stuck sort yields false, and PROJ inference (:957-973) then
;; permits the data projection. Fix: throw when `t` is not a Sort (Lean's ensure_sort) and test
;; the level with `Level.isZero` (normalizing) rather than the syntactic tag.

(defn- with-owner
  "Env extended with the #14807 construction on top of the gadget:
     ksP : Prop := ksA = ksB
     ksGate (h : ksP) : Type := Eq.rec (motive := fun _ _ => Type) Prop h   -- K-reduces to Prop
     inductive KsOwner (h : ksP) : ksGate h | mk (bit : Bool)                -- lives in Prop
     ksAsProp (h : ksP) : Prop := KsOwner h
     axiom ksWitness : ksA = 7                                               -- : ksP up to defeq
     ksProposition : Prop := ksAsProp ksWitness
   The sort of `KsOwner ksWitness` is `ksGate ksWitness`, stuck (ksA ≢ 7 blocks K-reduction)."
  [env]
  (let [eq1 (c "Eq" [l1])
        ksP-val (e/app* eq1 @Nat (c "ksA") (c "ksB"))
        env (admit env (env/mk-def (n "ksP") [] prop ksP-val :hints {:regular 3}))
        eq-rec (c "Eq.rec" (level-args env "Eq.rec" {"u" l2 "u_1" l1}))
        motive (lam "b" @Nat (lam "h" (e/app* eq1 @Nat (c "ksA") (bv 0)) type0))
        gate-body (lam "h" (c "ksP") (e/app* eq-rec @Nat (c "ksA") motive prop (c "ksB") (bv 0)))
        env (admit env (env/mk-def (n "ksGate") [] (e/arrow (c "ksP") type0) gate-body :hints {:regular 4}))
        Owner (n "KsOwner") mk (n "KsOwner.mk")
        env (declare-inductive
             env [] 1
             [(env/mk-induct Owner [] (pi "h" (c "ksP") (e/app (c "ksGate") (bv 0)))
                             :num-params 1 :num-indices 0 :all [Owner] :ctors [mk])]
             [(env/mk-ctor mk [] (pi "h" (c "ksP") (pi "bit" @Bool (e/app (c "KsOwner") (bv 1))))
                           Owner 0 1 1)])
        env (admit env (env/mk-def (n "ksAsProp") [] (e/arrow (c "ksP") prop)
                                   (lam "h" (c "ksP") (e/app (c "KsOwner") (bv 0))) :hints {:regular 5}))
        env (admit env (env/mk-axiom (n "ksWitness") [] (e/app* eq1 @Nat (c "ksA") (lit 7))))
        env (admit env (env/mk-def (n "ksProposition") [] prop
                                   (e/app (c "ksAsProp") (c "ksWitness")) :hints {:regular 6}))]
    env))

(def ^:private owner-env (delay (with-owner @gadget-env)))

(deftest pr14807-owner-fixture-is-a-genuine-proposition
  (let [env @owner-env
        rec ^ConstantInfo (env/lookup env (n "KsOwner.rec"))]
    (is (some? rec))
    (is (empty? (vec (.levelParams rec)))
        "KsOwner eliminates only into Prop — the kernel classified it as a proposition (upstream's guard)")
    (is (.isDefEq (fresh-tc env) (e/app (c "ksGate") (c "ksWitness")) (e/app (c "ksGate") (c "ksWitness"))))
    (let [stuck (whnf env (e/app (c "ksGate") (c "ksWitness")))]
      (is (not (e/sort? stuck)) "the sort of `KsOwner ksWitness` is stuck: K-reduction needs ksA ≡ 7"))))

(deftest pr14807-no-data-projection-out-of-a-stuck-sort-proposition
  (testing "upstream leanprover/lean4#14807 — `fun (p : ksProposition) => p.1 : Bool` extracts the
   Bool field of a proof (ksProposition : Prop). is_prop must be decided by ensure_sort, which
   fails on the stuck sort, instead of answering 'not a Prop'."
    (let [env @owner-env
          observe (env/mk-def (n "ksObserve") [] (e/arrow (c "ksProposition") @Bool)
                              (lam "p" (c "ksProposition") (e/proj (n "KsOwner") 0 (bv 0)))
                              :hints {:regular 7})]
      (is (some? (rejection env observe))
          "EXPOSED: isProp returns false on a stuck sort, so PROJ inference allows the data field"))))

;; --- Authoritative #14807 cases: the Kernel Arena's invalid-proof corpus -------------------
;;
;; https://github.com/leanprover/lean-kernel-arena tests/proj-of-subst-prop and
;; tests/rec-of-subst-prop (Apache-2.0; the latter is the exploit from leanprover/lean4#14847).
;; Both are the construction above with `Acc.rec` + an opaque accessibility proof as the
;; non-transitivity gadget, exported by lean4export (Lean v4.29.1) as the dependency closure of
;; the final `False` theorem; vendored under test-data/arena/. Every current arena checker
;; rejects them; the arena expects `outcome: reject`. `rec-of-subst-prop` recovers the data field
;; through the Prop-only RECURSOR (into `Fiber X := Acc emptyTypeRel X`, then `Acc.rec` into
;; Type), so it exercises the second is_prop site — Reducer's struct-eta of a recursor major
;; (Reducer.java:1313-1331, Lean's to_cnstr_when_structure) — not the projection guard.

(defn- arena-first-error
  "Replay an arena export in VERIFY mode; the first rejected declaration's name, or nil if the
   whole file is accepted."
  [file]
  (let [decls (:decls (parser/parse-ndjson-file file))
        {:keys [results]} (replay/replay decls :verify? true)]
    (:name (first (filter #(= :error (:status %)) results)))))

(deftest pr14807-arena-proj-of-subst-prop-is-rejected
  (testing "lean-kernel-arena tests/proj-of-subst-prop: the projection out of `PR14806Subst.proposition`
   (or the `inconsistent` theorem built from it) must be rejected"
    (let [bad (arena-first-error "test-data/arena/proj-of-subst-prop.ndjson")]
      (is (some? bad) "EXPOSED: the whole export is accepted, `inconsistent : False` included")
      (is (or (nil? bad) (re-find #"^PR14806Subst\.|^inconsistent$" bad))
          (str "the rejection must be inside the exploit, not the Init closure: " bad)))))

(deftest pr14807-arena-rec-of-subst-prop-is-rejected
  (testing "lean-kernel-arena tests/rec-of-subst-prop (leanprover/lean4#14847): eliminating the
   proposition `Issue.Owner gateWitness` with its own recursor must not hand out the Type field"
    (let [bad (arena-first-error "test-data/arena/rec-of-subst-prop.ndjson")]
      (is (some? bad) "EXPOSED: the whole export is accepted, `Issue.contradiction : False` included")
      (is (or (nil? bad) (re-find #"^Issue\." bad))
          (str "the rejection must be inside the exploit, not the Init closure: " bad)))))

;; ============================================================
;; #14808 — generated recursors and ι-rules are kernel-checked
;; ============================================================
;;
;; Upstream: `add_core` installed generated recursors unchecked; #14808 adds `check_recursors`:
;; (1) `tc().check(rec_type)`, (2) for every constructor, `lhs := rec params Cs minors indices
;; (ctor params fields)`, `whnf(lhs)` must have a type defeq to `infer(lhs)`.
;;
;; Ours: recursors reach the env only through InductiveBundleChecker. IMPORTED recursors are
;; validated against our generator (RecursorGenerator.checkAndDeclareRecursors :164-175:
;; type and every rule RHS must be structurally equal or defeq to the generated one; existing
;; test `reject-corrupt-imported-recursor-rule-test`) — a stronger check than #14808 for
;; imports. GENERATED recursors (nested aux blocks, InductiveChecker.generateAndCheckRecursors
;; :68-75) only pass checkRecursorDeclaration (TypeChecker.java:2466-2492: the type is a sort,
;; nfields matches) — no ι-rule type-preservation check. So the generator is trusted. The test
;; below applies Lean's check_recursors to our generated recursors for several shapes.

(defn- recursor-rules-type-preserving?
  "Lean #14808's check (2) for `rec-name` in `env`: every ι-rule is type-preserving."
  [env rec-name]
  (let [rec ^ConstantInfo (env/lookup env (n rec-name))
        lps (vec (.levelParams rec))
        tc (fresh-tc env lps)
        fresh! (fn [nm ty] (let [id (.nextFvarId tc)] (.addLocal tc id (str nm) ty) (e/fvar id)))
        peel (fn [ty k]
               (loop [ty ty k k fvs []]
                 (if (zero? k) [fvs ty]
                     (let [fv (fresh! (e/forall-name ty) (e/forall-type ty))]
                       (recur (e/instantiate1 (e/forall-body ty) fv) (dec k) (conj fvs fv))))))
        np (.numParams rec) nmot (.numMotives rec) nmin (.numMinors rec)
        [pre _] (peel (.type rec) (+ np nmot nmin))
        params (subvec pre 0 np)
        motives (subvec pre np (+ np nmot))
        minors (subvec pre (+ np nmot))
        rec-const (e/const' (n rec-name) (mapv lvl/param lps))]
    (every? (fn [^ConstantInfo$RecursorRule rule]
              (let [ctor ^ConstantInfo (env/lookup env (.ctor rule))
                    ctor-const (e/const' (.ctor rule) (mapv lvl/param (vec (.levelParams ctor))))
                    cty (reduce (fn [ty p] (e/instantiate1 (e/forall-body ty) p)) (.type ctor) params)
                    [fields res] (peel cty (.nfields rule))
                    indices (vec (drop np (e/get-app-args res)))
                    lhs (apply e/app* rec-const
                               (concat params motives minors indices
                                       [(apply e/app* ctor-const (concat params fields))]))
                    expected (.check tc lhs)
                    reduct (tc-whnf tc lhs)]
                (and (not (identical? reduct lhs))
                     (.isDefEq tc (.inferType tc reduct) expected))))
            (.rules rec))))

(deftest pr14808-generated-recursors-are-type-preserving
  (testing "Lean's check_recursors holds for our generated recursors (KsAc: large-eliminating
   predicate with an IH; KsOwner: Prop-only elimination with a data field) and for imported ones
   (Nat, List, Acc, Eq with K)"
    (let [env @owner-env]
      (doseq [r ["KsAc.rec" "KsOwner.rec" "Nat.rec" "List.rec" "Acc.rec" "Eq.rec"]]
        (is (recursor-rules-type-preserving? env r) r)))))

;; ============================================================
;; #12973 — theorems are opaque in the kernel
;; ============================================================
;;
;; Upstream: `declaration::has_value()` became `is_definition()` (was `is_theorem() ||
;; is_definition()`), so whnf / lazy delta never unfold a theorem.
;;
;; Ours: ConstantInfo.getValue (ConstantInfo.java:171-173) returns the value for THM too — its
;; docstring says so explicitly — and Reducer.tryUnfoldDef (Reducer.java:1599-1605) and
;; TypeChecker.deltaInfo (:1758-1762) key on getValue, so theorem bodies are delta-unfolded in
;; whnf and in lazy delta reduction. Not a soundness hole (theorem bodies are well typed), but a
;; behavioral divergence: opacity is the premise of the hot/cold term split in
;; .internal/MATHLIB_CATALOGUE.md. Being fixed on the main line; pinned here.

(deftest pr12973-theorems-are-not-delta-unfolded
  (testing "upstream leanprover/lean4#12973 — whnf of a theorem constant is the constant itself"
    (let [env (admit @E (env/mk-thm (n "ksThm") [] (c "True") (c "True.intro")))]
      (is (e/const? (whnf env (c "Nat.zero_add"))) "EXPOSED: imported theorem body unfolds (getValue returns THM values)")
      (is (e/const? (whnf env (c "ksThm"))) "EXPOSED: freshly admitted theorem body unfolds"))))

(deftest pr12973-opaques-are-not-delta-unfolded
  (testing "control: an `opaque` (which getValue already refuses) stays stuck"
    (let [env (admit @E (env/mk-opaque (n "ksOpq") [] @Nat (lit 3)))]
      (is (e/const? (whnf env (c "ksOpq")))))))

;; ============================================================
;; #14577 — arguments to phantom parameters of nesting inductives are type-checked
;; ============================================================
;;
;; Upstream: nested-inductive elimination replaces every nested occurrence `I Ds` by an
;; auxiliary type; the parametric arguments `Ds` are dropped from the auxiliary block, so an
;; ill-typed argument to a PHANTOM parameter (one no constructor mentions) escaped checking.
;; #14577 type-checks each replaced `I Ds` in the final environment.
;;
;; Ours: InductiveBundleChecker.checkBundle (InductiveBundleChecker.java:20-70) — on the nested
;; path it checks the AUX bundle, restores, and calls InductiveChecker.admitOriginalBundle
;; (InductiveChecker.java:362-368), which `addConstant`s the ORIGINAL constructors without ever
;; type-checking their types; NestedInductiveEliminator (:437-460) never type-checks the nested
;; app it replaces. The non-nested path DOES check constructor types (checkConstructors :141-145).

(defn- with-phantom-types
  "KsC (structure with a Bool field), KsW (another one-field type), KsL (α : Type) (b : Bool) : Type
   whose single constructor mentions neither parameter — both are phantom."
  [env]
  (let [decl1 (fn [env nm ty ctor-nm ctor-ty nparams nfields]
                (env/check-inductive-bundle
                 env (env/mk-inductive-bundle
                      [] nparams false
                      [(env/mk-induct (n nm) [] ty :num-params nparams :num-indices 0
                                      :all [(n nm)] :ctors [(n ctor-nm)])]
                      [(env/mk-ctor (n ctor-nm) [] ctor-ty (n nm) 0 nparams nfields)]
                      [])
                 fuel))
        env (decl1 env "KsC" type0 "KsC.mk" (e/arrow @Bool (c "KsC")) 0 1)
        env (decl1 env "KsW" type0 "KsW.mk" (e/arrow @Bool (c "KsW")) 0 1)
        env (decl1 env "KsL" (pi "α" type0 (pi "b" @Bool type0)) "KsL.mk"
                   (pi "α" type0 (pi "b" @Bool (e/app* (c "KsL") (bv 1) (bv 0)))) 2 0)]
    env))

(def ^:private phantom-env (delay (with-phantom-types @E)))

(defn- nesting-bundle
  "inductive KsE (w : KsW) : Type | mk (l : KsL (KsE w) <bad>) : KsE w — `bad` is the argument to
   KsL's phantom Bool parameter. `num-nested` selects the kernel path (Lean always eliminates)."
  [bad num-nested]
  (let [KsE (n "KsE") mk (n "KsE.mk")]
    (env/mk-inductive-bundle
     [] 1 false
     [(env/mk-induct KsE [] (pi "w" (c "KsW") type0)
                     :num-params 1 :num-indices 0 :all [KsE] :ctors [mk] :num-nested num-nested)]
     [(env/mk-ctor mk []
                   (pi "w" (c "KsW")
                       (pi "l" (e/app* (c "KsL") (e/app (c "KsE") (bv 0)) bad)
                           (e/app (c "KsE") (bv 1))))
                   KsE 0 1 1)]
     [])))

(deftest pr14577-control-non-nested-path-checks-the-argument
  (testing "with num-nested = 0 the plain path type-checks the constructor and rejects `Nat.zero : Bool`"
    (is (some? (bundle-rejection @phantom-env (nesting-bundle (c "Nat.zero") 0)))))
  (testing "a well-typed phantom argument is accepted on the nested path"
    (is (nil? (bundle-rejection @phantom-env (nesting-bundle (c "Bool.true") 1))))))

(deftest pr14577-nested-phantom-parameter-argument-is-type-checked
  (testing "upstream leanprover/lean4#14577 — `KsL (KsE w) Nat.zero` passes a Nat where KsL expects a
   Bool; the argument is dropped by nested elimination and must still be rejected"
    (is (some? (bundle-rejection @phantom-env (nesting-bundle (c "Nat.zero") 1)))
        "EXPOSED: admitOriginalBundle adds the original constructor unchecked"))
  (testing "upstream's exact input: `w.1.1` with w : KsW is an invalid projection (KsW is not KsC)"
    (let [w-1-1 (e/proj (n "KsC") 0 (e/proj (n "KsC") 0 (bv 0)))]
      (is (some? (bundle-rejection @phantom-env (nesting-bundle w-1-1 1)))
          "EXPOSED: the ill-typed projection lives only in the dropped phantom argument"))))

;; ============================================================
;; #14613 / #14615 — Prop is recognized up to universe normalization
;; ============================================================
;;
;; Upstream: `is_prop` compared the sort against `Prop` syntactically, and inductive.cpp used
;; `is_zero` on the result level; `Sort (imax 1 0)` (built with Lean-side `Level` constructors,
;; which bypass the C++ `mk_imax`) therefore counted as data and its Bool field could be
;; projected out of a proof. Both now use `normalizes_to_zero`.
;;
;; Ours: universe levels are canonicalized AT CONSTRUCTION — Level.imax (Level.java:91-102) is
;; Lean's mk_imax (`imax l 0 → 0`, `imax 0 l → l`, ...), Level.max (:72-89) is mk_max,
;; Level.instantiate (:207-230) rebuilds through them, the NDJSON parser (parser.clj:121) and the
;; PSS store (storage.clj:85) construct through them, and the raw constructors (imaxRaw, the
;; Level constructor) are private. So `Sort (imax 1 0)` IS `Sort 0` in our kernel and the
;; syntactic zero test in TypeChecker.isProp (:557) cannot be fooled by any public input.
;; (Level.isZero at :548 is the normalizing predicate Lean now uses; validateConstructor uses it.)

(deftest pr14613-levels-normalize-at-construction
  (is (lvl/level-zero? (lvl/imax l1 l0)) "imax 1 0 is built as zero (mk_imax)")
  (is (lvl/level-zero? (lvl/level-max l0 l0)))
  (is (lvl/level-zero? (lvl/imax (lvl/param (n "u")) l0)) "imax u 0 = 0 for every u")
  (is (lvl/level-zero? (lvl/instantiate (lvl/imax l1 (lvl/param (n "v"))) {(n "v") l0}))
      "instantiation re-normalizes: (imax 1 v)[v := 0] = 0")
  (is (Level/isZero (lvl/imax l1 l0)))
  (is (not (Level/isZero (lvl/param (n "u")))) "parameters are not provably zero (Lean: normalizes_to_zero fails)"))

(deftest pr14615-imax-prop-inductive-is-an-inductive-predicate
  (testing "kernelImaxPropInductive.lean — `inductive KsImaxP : Sort (imax 1 0) | mk (b : Bool)` is a
   proposition: the data field is allowed and the recursor eliminates only into Prop, exactly as
   for `Sort 0`; and projecting the field out of a proof is rejected"
    (let [env @E
          P (n "KsImaxP") mk (n "KsImaxP.mk")
          env (declare-inductive env [] 0
                                 [(env/mk-induct P [] (e/sort' (lvl/imax l1 l0))
                                                 :num-params 0 :num-indices 0 :all [P] :ctors [mk])]
                                 [(env/mk-ctor mk [] (e/arrow @Bool (c "KsImaxP")) P 0 0 1)])
          rec ^ConstantInfo (env/lookup env (n "KsImaxP.rec"))]
      (is (empty? (vec (.levelParams rec))) "Prop-only elimination")
      (is (nil? (rejection env (env/mk-def (n "ksImaxAsProp") [] prop (c "KsImaxP")))))
      (is (some? (rejection env (env/mk-def (n "ksImaxLeak") [] (e/arrow (c "KsImaxP") @Bool)
                                            (lam "proof" (c "KsImaxP") (e/proj P 0 (bv 0))))))
          "no data projection out of a proof"))))

;; ============================================================
;; #14849 — Nat numeral size bound
;; ============================================================
;;
;; Upstream: numerals the kernel computes or receives are bounded by LEAN_NAT_MAX_SIZE (128 MB
;; default): checked on literals at inference (`infer_lit`), on add/sub/mul results, before
;; `Nat.pow` (`size(base) * exp` and `exp` must fit 32 bits) and `Nat.shiftLeft`. Exceeding the
;; bound is a prompt kernel error.
;;
;; Ours: Reducer.reduceNatBinop (Reducer.java:1095-1131) keeps the PRE-fix `ReducePowMaxExp`
;; (1<<24) on pow / shiftLeft / shiftRight and returns null past it — a structural fallback that
;; unfolds Nat.pow through Nat.rec while the literal grows (bounded only by fuel; each step
;; carries the whole literal). add/sub/mul results are unbounded; literals are unbounded at
;; inference. The only hard stop is BigInteger's own 2^31-bit magnitude limit
;; (ArithmeticException), reached after allocating up to hundreds of MB. Not a soundness hole —
;; a resource-exhaustion divergence.

(defn- reduce-nat-binop [op a b]
  (let [m (doto (.getDeclaredMethod Reducer "reduceNatBinop"
                                    (into-array Class [Name BigInteger BigInteger]))
            (.setAccessible true))]
    (.invoke m nil (object-array [op (biginteger a) (biginteger b)]))))

(def ^:private pow-max-exp (bit-shift-left 1 24))

(deftest pr14849-native-reduction-within-the-size-bound
  (testing "pow/shiftLeft evaluate natively whenever the RESULT fits the size bound (lean4#14849):
   the guard is a size estimate checked before evaluating, not the pre-fix 1<<24 exponent cap"
    (let [r (reduce-nat-binop Name/NAT_POW 2 pow-max-exp)]
      (is (e/lit-nat? r))
      (is (= (inc pow-max-exp) (.bitLength ^BigInteger (e/lit-nat-val r)))))
    (let [r (reduce-nat-binop Name/NAT_POW 2 (inc pow-max-exp))]
      (is (e/lit-nat? r) "past the old 1<<24 exponent cap but a 2 MB result: computed exactly")
      (is (= (+ 2 pow-max-exp) (.bitLength ^BigInteger (e/lit-nat-val r)))))
    (is (e/lit-nat? (reduce-nat-binop Name/NAT_SHIFT_LEFT 1 (inc pow-max-exp))))
    (is (= 1 (e/lit-nat-val (reduce-nat-binop Name/NAT_POW 1 4294967296))) "base 1 is exact for any exponent")
    (is (= 0 (e/lit-nat-val (reduce-nat-binop Name/NAT_POW 0 4294967296))) "base 0 is exact for any exponent")))

(deftest pr14849-oversized-numerals-are-rejected-promptly
  (testing "upstream leanprover/lean4#14849 — `2 ^ 4294967296` (exponent does not fit 32 bits) and
   `2 ^ (2^31)` (result over 128 MB) are prompt kernel errors, not a structural fallback"
    (is (thrown? Exception (reduce-nat-binop Name/NAT_POW 2 4294967296))
        "EXPOSED: returns null and falls back to unfolding Nat.pow structurally")
    (is (thrown? Exception (reduce-nat-binop Name/NAT_POW 2 (bit-shift-left 1 31)))
        "EXPOSED: no result-size bound"))
  (testing "a literal over 128 MB entering the kernel is rejected at inference (infer_lit)"
    (let [huge (.shiftLeft BigInteger/ONE (bit-shift-left 1 30))]
      (is (some? (rejection @E (env/mk-def (n "ksHugeLit") [] @Nat (e/lit-nat huge))))
          "EXPOSED: LIT_NAT inference has no size bound"))))

;; ============================================================
;; #14953 — Lean.reduceBool / reduceNat / ofReduceBool / trustCompiler deleted
;; ============================================================
;;
;; Upstream removed `reduce_native` from the kernel (type_checker.cpp:596-612 in the pre-fix
;; baseline: `Lean.reduceBool c` invoked the interpreter) together with the `trustCompiler`
;; axiom. Ours never had a native-reduction hook: grep of src/ src-java/ for reduceBool /
;; reduceNat / ofReduceBool / trustCompiler finds only the GMP-style Nat-literal reduction
;; (`tryReduceNat`, trace label "reduceNat"), which is `reduce_nat`, not `reduce_native`; the
;; bundled Init tier does not contain the four constants. Nothing to delete.

(deftest pr14953-no-native-reduction-hook
  (let [env @E]
    (doseq [s ["Lean.reduceBool" "Lean.reduceNat" "Lean.ofReduceBool" "Lean.trustCompiler"]]
      (is (nil? (env/lookup env (n s))) s))
    (testing "an opaque named Lean.reduceBool is treated like any other opaque: never evaluated"
      (let [env (admit env (env/mk-opaque (n "Lean.reduceBool") [] (e/arrow @Bool @Bool)
                                          (lam "b" @Bool (bv 0))))
            call (e/app (c "Lean.reduceBool") (c "Bool.false"))
            w (whnf env call)]
        (is (e/app? w))
        (is (= (n "Lean.reduceBool") (e/const-name (e/get-app-fn w))))
        (is (not (.isDefEq (fresh-tc env) call (c "Bool.false"))))))))
