#!/usr/bin/env python3
"""Regenerate scripts/init-store-roots.txt -- the root manifest for the bundled Init store.

The bundled store is the transitive dependency closure of that manifest (see
scripts/regen-bundled-store.sh). This script is how the manifest itself is derived, so that
widening the tier is a reproducible operation rather than a hand edit nobody can reconstruct
-- which is exactly how the store drifted before (it was a raw `head -n 200000` of a full
`lean4export Init` dump, with no script and no record of the cut).

Roots are the union of:
  1. every declaration already in the current bundled store, so the tier only ever grows
  2. the whole `Lean.Omega.*` namespace -- omega's certificate lemmas
  3. every constant named in the `omega-names` table in src/ansatz/tactic/omega_proof.clj
  4. every constant that file names inline via `(name/from-string "...")`
  5. a hand-maintained EXTRAS list (below): correct core spellings for names omega_proof.clj
     gets wrong, plus the bmod/div-bound machinery its proof builder needs

minus the EXCLUDE set, which must stay out or well-founded recursion breaks (see below).

Usage:
    python3 scripts/init-store-roots.py [FULL_INIT_NDJSON]

FULL_INIT_NDJSON is a complete `lean4export Init` dump used as the existence oracle: a root
that does not name a real constant makes lean4export abort, so unknown names are dropped
with a report. It defaults to test-data/init.ndjson; produce one with

    cd ../lean4export && lake env ./.lake/build/bin/lean4export Init > ../ansatz/test-data/init.ndjson

Then re-run scripts/regen-bundled-store.sh to rebuild the store from the new manifest.
"""
import gzip
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "init-store-roots.txt")
STORE = os.path.join(PROJECT, "resources", "ansatz", "init-medium.ndjson.gz")
OMEGA_SRC = [
    os.path.join(PROJECT, "src", "ansatz", "tactic", "omega_proof.clj"),
    os.path.join(PROJECT, "src", "ansatz", "tactic", "omega.clj"),
] + [
    os.path.join(PROJECT, "src", "ansatz", "tactic", "omega", f)
    for f in sorted(os.listdir(os.path.join(PROJECT, "src", "ansatz", "tactic", "omega")))
    if f.endswith(".clj")
]
DEFAULT_ORACLE = os.path.join(PROJECT, "test-data", "init.ndjson")

# ---------------------------------------------------------------------------
# ansatz ships its OWN minimal `SizeOf` and `Prod.Lex` developments in
# resources/ansatz/{sizeof,lex}-prelude.ndjson.gz, and src/ansatz/wf.clj's well-founded
# recursion encoder is built against those. If the Init store also defines them the two
# collide and `:termination-by` proofs stop discharging with `:termination-wf-encode-failed`.
# The previous store excluded them only by accident of being a truncation; keep it explicit.
EXCLUDE = re.compile(
    r"(\._sizeOf_1|\._sizeOf_inst|\.sizeOf_spec)$"    # per-inductive sizeOf auxiliaries
    r"|^SizeOf(\.|$)|^instSizeOf"                      # the SizeOf class itself
    r"|^Prod\.Lex(\.|$)"                               # lexicographic order on pairs
    r"|^Lean\.Omega\.Prod\."                           # the only Lean.Omega users of Prod.Lex
)

# Correct core spellings for constants omega_proof.clj references under Mathlib names or
# typos, plus the machinery its :bmod case and add-div-bounds Int branch build terms out of.
# Shipping the correct names means fixing those references is a pure rename, no store change.
EXTRAS = [
    "Decidable.not_and_iff_not_or_not",      # for `not_and_or`
    "Classical.not_and_iff_not_or_not",
    "Classical.not_imp",                     # for `not_imp`
    "Decidable.not_imp_iff_and_not",
    "Decidable.iff_iff_and_or_not_and_not",  # for `iff_iff_and_or_not_and_not`
    "Int.ofNat_eq_natCast",                  # for `Int.ofNat.eq_def` (Int.ofNat is a ctor,
                                             # so it has no equation lemma)
    # bmod (hard-equality elimination) support -- Lean.Omega.bmod_sat's statement and the
    # terms extract-proof's :bmod case assembles around it
    "Lean.Omega.Coeffs.bmod",
    "Lean.Omega.Coeffs.bmod_length",
    "Lean.Omega.Coeffs.bmod_dot_sub_dot_bmod",
    "Lean.Omega.Coeffs.dvd_bmod_dot_sub_dot_bmod",
    "Lean.Omega.Coeffs.get",
    "Lean.Omega.Coeffs.set",
    "of_decide_eq_true",
    "Decidable.decide",
    "Nat.decLe",
    "List.length",
    "instHMul", "instHAdd", "Int.instMul", "Int.instAdd",
    # Int division/modulo bounds (omega_proof.clj's add-div-bounds Int branch)
    "Int.mul_ediv_self_le", "Int.lt_mul_ediv_self_add",
    "Int.emod_emod_of_dvd", "Int.ediv_add_emod",
]

HEADER = """\
# Root manifest for the bundled "medium" Init store. GENERATED by scripts/init-store-roots.py
# -- edit EXTRAS/EXCLUDE there rather than hand-editing this file.
#
# The bundled store (resources/ansatz/init-medium.ndjson.gz) is the transitive dependency
# closure of these roots, produced by scripts/regen-bundled-store.sh. Closure under
# dependencies is guaranteed by lean4export, so the export always replays cleanly through
# the ansatz kernel. Blank lines and `#` comments are ignored; everything else is passed to
# lean4export after a `--` separator and must name a constant that exists in `Init` at the
# toolchain pinned in ../lean4export/lean-toolchain (currently leanprover/lean4:v4.29.0-rc2).
#
# Five names referenced by omega_proof.clj do NOT exist in Lean core's `Init` under those
# spellings -- they are Mathlib spellings or typos -- and so cannot be roots. The correct
# core constants ARE in this manifest, so fixing each reference is a rename with no store
# change needed:
#
#   omega_proof.clj spelling            core constant shipped here
#   ----------------------------------  ------------------------------------------
#   not_and_or                          Decidable.not_and_iff_not_or_not
#                                       Classical.not_and_iff_not_or_not
#   not_imp                             Classical.not_imp
#                                       Decidable.not_imp_iff_and_not
#   iff_iff_and_or_not_and_not          Decidable.iff_iff_and_or_not_and_not
#   Int.ofNat.eq_def                    Int.ofNat_eq_natCast
#   Lean.Omega.Coeffs.bmod_coeffs       Lean.Omega.bmod_coeffs  (already a root; this is
#                                       the name `Lean.Omega.bmod_sat`'s own statement uses)
#
# DELIBERATE OMISSIONS -- do not "helpfully" add these. ansatz ships its own minimal
# `SizeOf` and `Prod.Lex` developments in resources/ansatz/{sizeof,lex}-prelude.ndjson.gz,
# and src/ansatz/wf.clj's well-founded recursion encoder is built against those. If the Init
# store also defines them the two collide and `:termination-by` proofs stop discharging with
# `:termination-wf-encode-failed`. The closure therefore excludes SizeOf and its instances,
# every `*._sizeOf_1` / `*._sizeOf_inst` / `*.sizeOf_spec` auxiliary, `Prod.Lex` and its
# eliminators, and `Lean.Omega.Prod.of_lex` / `of_not_lex`. The previous store excluded
# these too -- by accident, being a truncation -- which is why the dependency went unnoticed.
"""

DECL_KEYS = ("def", "thm", "axiom", "opaque", "quot")


def _open(path):
    if path.endswith(".gz"):
        return io.TextIOWrapper(gzip.open(path, "rb"), encoding="utf-8")
    return open(path, encoding="utf-8")


def declarations(path, roots_only=False):
    """Yield the constant names declared by a lean4export NDJSON dump. With roots_only,
    yield inductive type names but not their constructors/recursors (lean4export re-derives
    those from the type, and they are not valid standalone roots)."""
    names = {0: ""}
    with _open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            if "in" in obj:
                idx = obj["in"]
                if "str" in obj:
                    pre = names.get(obj["str"]["pre"], "")
                    part = obj["str"]["str"]
                elif "num" in obj:
                    pre = names.get(obj["num"]["pre"], "")
                    part = str(obj["num"].get("i"))
                else:
                    continue
                names[idx] = (pre + "." + part) if pre else part
                continue
            for key in DECL_KEYS:
                if key in obj:
                    yield names.get(obj[key]["name"], "?")
                    break
            else:
                if "inductive" in obj:
                    blk = obj["inductive"]
                    groups = ["types"] if roots_only else ["types", "ctors", "recs"]
                    for group in groups:
                        for item in blk.get(group, []):
                            yield names.get(item["name"], "?")


def omega_names():
    """Every constant omega's proof builder names -- via omega_proof.clj's `omega-names`
    table, or inline as `(name/from-string "...")` anywhere under src/ansatz/tactic/omega*."""
    table, inline = set(), set()
    for path in OMEGA_SRC:
        src = open(path, encoding="utf-8").read()
        table |= set(re.findall(r'\(n\s+"([^"]+)"\)', src))
        inline |= set(re.findall(r'name/from-string\s+"([^"]+)"', src))
    return table, inline


def main():
    oracle = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ORACLE
    if not os.path.exists(oracle):
        sys.exit(f"existence oracle {oracle} not found -- see this script's docstring")

    exists = set(declarations(oracle))
    report = {}

    roots = set(declarations(STORE, roots_only=True))
    report["current store"] = len(roots)

    omega_ns = {n for n in exists if n.startswith("Lean.Omega.")}
    roots |= omega_ns
    report["Lean.Omega.*"] = len(omega_ns)

    table, inline = omega_names()
    roots |= table | inline
    report["omega-names table"] = len(table)
    report["omega inline refs"] = len(inline)

    roots |= set(EXTRAS)
    report["extras"] = len(EXTRAS)

    excluded = sorted(n for n in roots if EXCLUDE.search(n))
    roots -= set(excluded)
    report["excluded (prelude clash)"] = len(excluded)

    present = sorted(n for n in roots if n in exists)
    absent = sorted(n for n in roots if n not in exists)

    for key, val in report.items():
        print(f"  {key:<26} {val}", file=sys.stderr)
    print(f"  {'roots written':<26} {len(present)}", file=sys.stderr)
    print(f"  {'dropped (not in Init)':<26} {len(absent)}", file=sys.stderr)
    for name in absent:
        print(f"    ABSENT {name}", file=sys.stderr)

    with open(MANIFEST, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        for name in present:
            fh.write(name + "\n")
    print(f"wrote {len(present)} roots to {MANIFEST}", file=sys.stderr)


if __name__ == "__main__":
    main()
