#!/usr/bin/env bash
# Regenerate the BUNDLED Init store shipped in the jar:
#   resources/ansatz/init-medium.ndjson.gz   (the kernel export: types + values)
#   test-data/init-medium.ndjson             (uncompressed dev copy; ~20 tests read it directly)
# and then co-generate the two metadata corpora that must never drift from it:
#   resources/ansatz/init-attrs.ndjson.gz    (via scripts/regen-bundled-attrs.sh)
#   resources/ansatz/init-matchers.ndjson.gz
#
# ---------------------------------------------------------------------------
# WHAT THE "medium" TIER IS
# ---------------------------------------------------------------------------
# The tier is the **transitive dependency closure of an explicit root set**, listed in
#   scripts/init-store-roots.txt
# lean4export takes those roots after a `--` separator and emits every constant they
# depend on, in dependency order. Closure-under-dependencies is therefore guaranteed by
# construction: the export can never mention a constant it has not already defined, so
# the result always replays cleanly through the ansatz kernel.
#
# ---------------------------------------------------------------------------
# WHY THIS SCRIPT EXISTS
# ---------------------------------------------------------------------------
# It did not, and that is exactly how the store drifted. The previously bundled store was
# byte-identical to `head -n 200000` of a full `lean4export Init` dump — a raw prefix
# truncation with no script, no root list, and no record of the cut. A prefix happens to be
# dependency-closed (the dump is topologically ordered), so it loaded fine and nobody
# noticed; but the cut fell at an arbitrary point that excluded ~20 constants the omega
# tactic references, including all of `Lean.Omega.bmod_*`. Because
# `ansatz.attrs/import-attrs` and `ansatz.matchers/import-matchers` silently skip names
# absent from the env, and `add-div-bounds` swallows lookup failures in a bare
# `catch Exception`, the gap degraded omega's capabilities without ever raising an error.
#
# Widening the prefix is not a viable fix: `Lean.Omega.bmod_sat` sits at line 5,315,838 of
# the 6,054,467-line full dump, so a prefix reaching it would carry 45,939 of Init's 54,335
# constants (85% of Init, ~285 MB raw). The closure of the root set is 3,432 constants.
#
# ---------------------------------------------------------------------------
# WIDENING THE TIER
# ---------------------------------------------------------------------------
# Add names to scripts/init-store-roots.txt and re-run this script. Roots must exist in
# `Init` at the pinned toolchain; lean4export aborts on an unknown name. Blank lines and
# `#` comments in the manifest are ignored.
#
# The manifest itself is generated by scripts/init-store-roots.py, which is where the tier
# rule lives: the union of the current store's declarations (so the tier never regresses),
# the whole `Lean.Omega.*` namespace, every constant omega's proof builder names, and a
# hand-maintained EXTRAS list -- minus an EXCLUDE set that must stay out because ansatz ships
# its own `SizeOf` and `Prod.Lex` preludes. Run that script, then this one.
#
# ---------------------------------------------------------------------------
# TOOLCHAIN
# ---------------------------------------------------------------------------
# Run from the SAME ../lean4export checkout that scripts/regen-bundled-attrs.sh uses; this
# script invokes that script at the end so all three artifacts are co-generated. The export
# is deterministic: the same lean4export binary + toolchain reproduces the dump byte for
# byte. Note that `--export-mdata` is deliberately NOT passed — the bundled store has never
# carried mdata wrappers, and adding them changes every expression index.
#
# `lake` must be on PATH (elan installs it under ~/.elan/bin, which is not always exported).
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PARENT_DIR="$(dirname "$PROJECT_DIR")"
# Deliberately not overridable: scripts/regen-bundled-attrs.sh, invoked at the end, hardcodes
# this same path, and the whole point is that all three artifacts come from one checkout.
LEAN4EXPORT="$PARENT_DIR/lean4export"
ROOTS="$PROJECT_DIR/scripts/init-store-roots.txt"
OUT_GZ="$PROJECT_DIR/resources/ansatz/init-medium.ndjson.gz"
OUT_RAW="$PROJECT_DIR/test-data/init-medium.ndjson"

if [ ! -d "$LEAN4EXPORT" ]; then
    echo "ERROR: $LEAN4EXPORT not found. Clone it (see scripts/setup-mathlib.sh) and \`lake build\` it." >&2
    exit 1
fi
BIN="$LEAN4EXPORT/.lake/build/bin/lean4export"
if [ ! -x "$BIN" ]; then
    echo "ERROR: $BIN not built. Run \`lake build\` in $LEAN4EXPORT." >&2
    exit 1
fi
if [ ! -f "$ROOTS" ]; then
    echo "ERROR: root manifest $ROOTS not found." >&2
    exit 1
fi

TC="$(cat "$LEAN4EXPORT/lean-toolchain" 2>/dev/null || echo '?')"
NROOTS="$(grep -vE '^\s*(#|$)' "$ROOTS" | wc -l)"

echo ">>> Exporting the closure of $NROOTS roots from $LEAN4EXPORT (toolchain $TC)"
mkdir -p "$(dirname "$OUT_RAW")" "$(dirname "$OUT_GZ")"
# shellcheck disable=SC2046  # word splitting is how the root list is passed
(cd "$LEAN4EXPORT" && lake env "$BIN" Init -- $(grep -vE '^\s*(#|$)' "$ROOTS")) > "$OUT_RAW"

gzip -9 -c "$OUT_RAW" > "$OUT_GZ"
sync "$OUT_RAW" "$OUT_GZ" 2>/dev/null || true
# `du` under delayed allocation can read 1.0K on a file that has not hit disk yet; ask for
# the apparent size so the numbers in the log are the ones that matter.
echo "    Wrote $OUT_RAW ($(wc -l < "$OUT_RAW") lines, $(du -h --apparent-size "$OUT_RAW" | cut -f1))"
echo "    Wrote $OUT_GZ ($(du -h --apparent-size "$OUT_GZ" | cut -f1), toolchain $TC)"
echo ""

echo ">>> Co-generating attrs + matchers from the same checkout"
"$PROJECT_DIR/scripts/regen-bundled-attrs.sh"
echo ""
echo ">>> Done. Verify with:"
echo "    clj -J-Xmx3g -M:test --namespace ansatz.bundled-store-roots-test"
